require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoisasController do

  # This should return the minimal set of attributes required to create a valid
  # Coisa. As you add validations to Coisa, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # describe "GET index" do
  #   it "assigns all coisas as @coisas" do
  #     coisa = Coisa.create! valid_attributes
  #     get :index
  #     assigns(:coisas).should eq([coisa])
  #   end
  # end
  # 
  # describe "GET show" do
  #   it "assigns the requested coisa as @coisa" do
  #     coisa = Coisa.create! valid_attributes
  #     get :show, :id => coisa.id
  #     assigns(:coisa).should eq(coisa)
  #   end
  # end
  # 
  # describe "GET new" do
  #   it "assigns a new coisa as @coisa" do
  #     get :new
  #     assigns(:coisa).should be_a_new(Coisa)
  #   end
  # end
  # 
  # describe "GET edit" do
  #   it "assigns the requested coisa as @coisa" do
  #     coisa = Coisa.create! valid_attributes
  #     get :edit, :id => coisa.id
  #     assigns(:coisa).should eq(coisa)
  #   end
  # end
  # 
  # describe "POST create" do
  #   describe "with valid params" do
  #     it "creates a new Coisa" do
  #       expect {
  #         post :create, :coisa => valid_attributes
  #       }.to change(Coisa, :count).by(1)
  #     end
  # 
  #     it "assigns a newly created coisa as @coisa" do
  #       post :create, :coisa => valid_attributes
  #       assigns(:coisa).should be_a(Coisa)
  #       assigns(:coisa).should be_persisted
  #     end
  # 
  #     it "redirects to the created coisa" do
  #       post :create, :coisa => valid_attributes
  #       response.should redirect_to(Coisa.last)
  #     end
  #   end
  # 
  #   describe "with invalid params" do
  #     it "assigns a newly created but unsaved coisa as @coisa" do
  #       # Trigger the behavior that occurs when invalid params are submitted
  #       Coisa.any_instance.stub(:save).and_return(false)
  #       post :create, :coisa => {}
  #       assigns(:coisa).should be_a_new(Coisa)
  #     end
  # 
  #     it "re-renders the 'new' template" do
  #       # Trigger the behavior that occurs when invalid params are submitted
  #       Coisa.any_instance.stub(:save).and_return(false)
  #       post :create, :coisa => {}
  #       response.should render_template("new")
  #     end
  #   end
  # end
  # 
  # describe "PUT update" do
  #   describe "with valid params" do
  #     it "updates the requested coisa" do
  #       coisa = Coisa.create! valid_attributes
  #       # Assuming there are no other coisas in the database, this
  #       # specifies that the Coisa created on the previous line
  #       # receives the :update_attributes message with whatever params are
  #       # submitted in the request.
  #       Coisa.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
  #       put :update, :id => coisa.id, :coisa => {'these' => 'params'}
  #     end
  # 
  #     it "assigns the requested coisa as @coisa" do
  #       coisa = Coisa.create! valid_attributes
  #       put :update, :id => coisa.id, :coisa => valid_attributes
  #       assigns(:coisa).should eq(coisa)
  #     end
  # 
  #     it "redirects to the coisa" do
  #       coisa = Coisa.create! valid_attributes
  #       put :update, :id => coisa.id, :coisa => valid_attributes
  #       response.should redirect_to(coisa)
  #     end
  #   end
  # 
  #   describe "with invalid params" do
  #     it "assigns the coisa as @coisa" do
  #       coisa = Coisa.create! valid_attributes
  #       # Trigger the behavior that occurs when invalid params are submitted
  #       Coisa.any_instance.stub(:save).and_return(false)
  #       put :update, :id => coisa.id, :coisa => {}
  #       assigns(:coisa).should eq(coisa)
  #     end
  # 
  #     it "re-renders the 'edit' template" do
  #       coisa = Coisa.create! valid_attributes
  #       # Trigger the behavior that occurs when invalid params are submitted
  #       Coisa.any_instance.stub(:save).and_return(false)
  #       put :update, :id => coisa.id, :coisa => {}
  #       response.should render_template("edit")
  #     end
  #   end
  # end
  # 
  # describe "DELETE destroy" do
  #   it "destroys the requested coisa" do
  #     coisa = Coisa.create! valid_attributes
  #     expect {
  #       delete :destroy, :id => coisa.id
  #     }.to change(Coisa, :count).by(-1)
  #   end
  # 
  #   it "redirects to the coisas list" do
  #     coisa = Coisa.create! valid_attributes
  #     delete :destroy, :id => coisa.id
  #     response.should redirect_to(coisas_url)
  #   end
  # end             

end
